### ISSUE TITLE
Does the VideosScore model really work?

### ISSUE THREAD

**Issue by crj1998** [TIGER-AI-Lab/VideoScore#4]
when i run the `examples/run_videoscore.py` directly, the result is
```
[2.297, 2.453, 2.906, 2.766, 2.531]
```
however, when i change the following `video_prompt ` to a empty string,
https://github.com/TIGER-AI-Lab/VideoScore/blob/03f12bc86e0017197478e6329b8dbb8720da7257/examples/run_videoscore.py#L52

the result is 
```
[2.234, 2.375, 2.828, 2.703, 2.391]
```

when the `video_prompt` is `a boat on the sea`, which is obviously not the content of the video.
the result is
```
[2.25, 2.359, 2.906, 2.859, 2.406]
```
 

i think this is a **not even wrong** model

**Comment by wenhuchen** [comment]
We will look into this. Thanks for reporting.

**Comment by WongChen** [comment]
Any update here?  Use my test case here, change prompt to a not-relevant-at-all prompt, however get same high score.

**Comment by wenhuchen** [comment]
@WongChen @crj1998 We have confirmed this issue.
I think it's reasonable because the training (caption, video) pairs were all generated from different models, so there alignments are all moderately high. There has not been any data consisting of unaligned pairs.
Therefore, we trained a new model with some additional unpaired data. The model is released under https://huggingface.co/TIGER-Lab/VideoScore-v1.1.

**Comment by crj1998** [comment]
> @WongChen @crj1998 We have confirmed this issue. I think it's reasonable because the training (caption, video) pairs were all generated from different models, so there alignments are all moderately high. There has not been any data consisting of unaligned pairs. Therefore, we trained a new model with some additional unpaired data. The model is released under https://huggingface.co/TIGER-Lab/VideoScore-v1.1.

Thank you so much for showing me your new and improved model so quickly. After testing, the results are indeed significantly better than the previous model
